apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: project-deploy
spec:
  # 3 Pods should exist at all times.
  replicas: 2
  selector:
    matchLabels:
      app: project-app
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: project-app
    spec:
      containers:
      - name: project-app
        # Run this image
        image: pav30/project:latest